'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("6868095b-b8eb-486c-8c18-8158c21ead17")> 

'Original file name:
'Generation date: 08/01/18 10:45:58
'''<summary>
'''There are no comments for Model1Container in the schema.
'''</summary>
Partial Public Class Model1Container
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=Model1Container", "Model1Container")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new Model1Container object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "Model1Container")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new Model1Container object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "Model1Container")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
End Class
